apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-kian
  namespace: argocd
spec:
  destination:
    namespace: coffee-kian
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
    path: charts/
    repoURL: https://github.com/techgardencode/kian.coffee.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
